let suggestions = [
    'andaman and nicobar islands',
    'puducherry',
    'dadra',
    'nagar haveli',
    'daman',
    'diu',   
    'ladak',
    'jammu and kashmir',
    'himachal pradesh',
    'chandigarh',
    'punjab',
    'haryana',
    'uttarakand',
    'delhi',
    'rajastan',
    'uttar pradesh',
    'varanasi',
    'kashi',
    'bihar',
    'madhya pradesh',
    'ujjain',
    'gujarat',
    'Dwarka',
    'goa',
    'maharastra',
    'telangana',
    'yadadri',
    'yadagiri gutta',
    'karnataka',
    'jog falls',
    'jog',
    'tamilnadu',
    'kerala',
    'lakshadweep',
    'andhra pradesh',
    'odisha',
    'konark',
    'suntemple',
    'chattisgar',
    'west bengal',
    'jharkhand',
    'sikkim',
    'assam',
    'meghalaya',
    'arunachal pradesh',
    'nagaland',
    'manipur',
    'mizoram',
    'tripura',
    'tajmahal'
];
